# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PMD:
    name: Run PMD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pmd maven
        run: mvn pmd:pmd

  spotBugs:
    name: Run Spotbugs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: choice spotbugs
        run: mvn spotbugs:spotbugs
      - name: generation xml report
        uses: actions/upload-artifact@v2
        with:
          name: reportXML
          path: target/spotbugsXml.xml

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/CHROME_DINO-1.0-SNAPSHOT.jar
          name: save_the_bird
